spring:
  datasource:
    url: jdbc:h2:mem:risk_register_test_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: false

  data:
    redis:
      repositories:
        enabled: false
